# Generated by Django 4.2.6 on 2023-10-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_image_delete_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='volume_in_cl',
            new_name='volume_in_centilitres',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='volume_in_lt',
            new_name='volume_in_litres',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='volume_in_ml',
            new_name='volume_in_millilitres',
        ),
    ]
